recorder:
  chunk_size: 65536
  frame_duration: 10
  flush_interval: 0

slicer:
  buffer_len: 100
  speech_len: 10
  non_speech_len: 1
  denoise_ratio_of_fragment: 0
  denoise_ratio_of_speech: 0.9
  slice_mode: vad

transcriber:
  number: 1
  # model_size: "Systran/faster-whisper-large-v3"
  model_size: "zh-plus/faster-whisper-large-v2-japanese-5k-steps"
  # model_size: "JhonVanced/whisper-large-v3-japanese-4k-steps-ct2"
  # model_size: "arc-r/faster-whisper-large-v2-mix-jp"
  local_files_only: false
  device: "cuda"
  lang_src: "japanese"
  beam_size: 15
  prompt: "翻訳する"


translator:
  lang_des: "en"
  phoneme:
    convert: true
    translate: false
  agent_pass:
    active: false
  agent_google:
    active: true
    domain: "hk"
    timeout: 5
  agent_poe:
    active: false
  agent_ollama:
    active: false


manifest:
  console:
    active: true
    phoneme: true
    transcribe: true
    translated: true
    performance: true
  barrage:
    active: true
    phoneme: true
    transcribe: true
    translated: true
    performance: false

gui:
  active: true
  width_ratio: 0.25
  barrage:
    max: 100
    roof: 100
    font:
      family: "Consolas"
      size: 13
      color: "#FFA500"
      background: "#000000"
    margin:
      x: 0
      y: 3
    offset:
      x: 20
      y: 120


poe:
  active: false
  token:
    b:
    lat:
  translate:
    all:
      id:
      prompt_type: ""


ollama:
  active: true
  host: "http://127.0.0.1:11434"
  translate:
    all:
      # id: "L3-lexi-8b-q6"
      id: "L3-dolphin-8b-q6"
      # id: "lq-14b"
      # id: "sakura-13b"
      prompt_type: ""

      # prompt_type: ""
      # prompt_type: "none"


