recorder:
  chunk_size: 512
  frame_duration: 10

slicer:
  slicer_maxlen: 30
  slicer_ratio: 0.5

transcriber:
  # model_size: "Systran/faster-whisper-large-v3"
  # model_size: "zh-plus/faster-whisper-large-v2-japanese-5k-steps"
  model_size: "JhonVanced/whisper-large-v3-japanese-4k-steps-ct2"
  local_files_only: true
  device: "cuda"
  lang_src: "ja"
  beam_size: 25
  prompt: "こんにちは"


translator:
  lang_des: "en"
  agent_google:
    active: true
    domain: "hk"
    timeout: 5
  agent_poe:
    active: false
  agent_ollama:
    active: true


renderer:
  console: true


poe:
  active: true
  token:
    b: ""
    lat: ""
  translate:
    all:
      id: "trans_BotIRT5PFUVID"
      prompt_type: ""


ollama:
  active: true
  host: "http://127.0.0.1:11434"
  translate:
    all:
      id: "L3-lexi-8b-q6"
      prompt_type: ""


