recorder:
  chunk_size: 4096
  frame_duration: 10

slicer:
  slicer_maxlen: 30
  slicer_ratio: 0.5

transcriber:
  # model_size: Systran/faster-whisper-large-v3
  model_size: "zh-plus/faster-whisper-large-v2-japanese-5k-steps"
  local_files_only: true
  device: "cuda"
  # prompt: "hello"
  prompt: "こんにちは"


translator:
  lang_des: "zh"
  agent_google:
    active: true
    domain: "hk"
    timeout: 5
  agent_poe:
    active: false
  agent_ollama:
    active: true


renderer:
  console: true


poe:
  token:
    b: "b"
    lat: "lat"
  translate:
    all: "*"


ollama:
  url: "http://127.0.0.1:11434/api/generate"
  translate:
    all: "*"
    ja: "*"
