recorder:
  chunk_size: 65536
  frame_duration: 10
  flush_interval: 0

slicer:
  buffer_len: 100
  speech_len: 10
  non_speech_len: 1
  denoise_ratio_of_fragment: 0
  denoise_ratio_of_speech: 0.9
  slice_mode: vad

transcriber:
  # model_size: "Systran/faster-whisper-large-v3"
  model_size: "zh-plus/faster-whisper-large-v2-japanese-5k-steps"
  # model_size: "JhonVanced/whisper-large-v3-japanese-4k-steps-ct2"
  # model_size: "arc-r/faster-whisper-large-v2-mix-jp"
  local_files_only: false
  device: "cuda"
  lang_src: "japanese"
  beam_size: 10
  prompt: "翻訳する"


translator:
  lang_des: "en"
  agent_google:
    active: true
    domain: "hk"
    timeout: 5
  agent_poe:
    active: false
  agent_ollama:
    active: false


manifest:
  show_transcribe: true
  show_translated: true
  show_performance: true

gui:
  active: true
  barrage:
    font:
      family: "Consolas"
      size: 12
      color: "#FFA500"
      background: "#000000"
    margin:
      x: 10
      y: 0






poe:
  active: true
  token:
    b: ""
    lat: ""
  translate:
    all:
      id: "-"
      prompt_type: ""


ollama:
  active: true
  host: "http://127.0.0.1:11434"
  translate:
    all:
      id: "L3-lexi-8b-q6"
      # id: "L3-dolphin-8b-q6"
      # id: "lq-14b"
      # id: "sakura-13b"
      prompt_type: ""

      # prompt_type: ""
      # prompt_type: "none"


