version: 1
formatters:
  simple:
    format: "%(asctime)s [%(name)s] %(levelname)s - %(message)s"
    encoding: utf-8
handlers:
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ../log/main.log
    maxBytes: 1000000
    backupCount: 10
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
root:
  level: INFO
  # handlers: [ file_handler, console_handler ]
  handlers: [ console_handler ]