version: 1
formatters:
  simple:
    format: "%(asctime)s [%(name)s] %(levelname)s - %(message)s"
handlers:
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ../log/main.log
    maxBytes: 1000000
    backupCount: 10
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
root:
  level: DEBUG
  handlers: [ file_handler, console_handler ]